### ISSUE TITLE
building with gradle-experimental, and it should be using CMake

### ISSUE THREAD

**Issue by gkasten** [google/walt#116]
Details at "Header files not found trying to build for Android"
https://groups.google.com/forum/#!topic/walt-discuss/ikdJ83ZBDDM

**Comment by ggfan** [comment]
the latest in the repo should be able to build.  https://github.com/google/walt/pull/115 would be the final touch up. The strategy:
- reuse the existing android.mk with Gradle's ndkBuild plugin
- application.mk is not used, intended to set up those variables inside app/build.gradle if needed in the future.
