### ISSUE TITLE
Add measurement of the display transition profile

### ISSUE THREAD

**Issue by kamrik** [google/walt#26]
It can take some 7ms for the display to go from black to white. It would be really good to see the shape of the brightness curve as a function of time.

Currently we also time the display transition based on a hard-coded threshold value (in arduino code). It's important to know where on the curve this threshold is for a particualar display.

**Comment by kamrik** [comment]
Partially done in 5680ac220a8c59ea85cf44b59fb0969cedf929f1

**Comment by sahiljain** [comment]
This has been implemented in #75
