### ISSUE TITLE
Allow end-to-end measurement on platforms where we can't (yet) synchronise clocks

### ISSUE THREAD

**Issue by kamrik** [google/walt#51]
While cloning the whole app is a lot of work, simplified end to end mesaurements can be prformed with fairly small efforts. In most cases it would only need some python scripts operating a WALT connected to a computer while the DUT only interacts with WALTs sensors.

**Comment by kamrik** [comment]
- Chrome app/site for chrome OS - we can sync using a separate binary in dev mode.
 - iPhone - can sync, needs work
 - Windows phone - didn't try

**Comment by sahiljain** [comment]
End-to-end measurements have been implemented in #107
