### ISSUE TITLE
WALT Android app hangs if Teensy not programmed

### ISSUE THREAD

**Issue by kamrik** [google/walt#6]
When plugging in a Teensy that is not programmed with the correct Arduino code, the android app starts and shows a blank screen for some 10 seconds.

It probably tries to sync clocks and doesn't get the expected replies.

**Comment by BenjaminFair** [comment]
#34 helps some, but we need to change the native code that syncs the clocks in order to fully fix this

**Comment by BenjaminFair** [comment]
This was fully fixed as a side effect of #35
